import express from 'express';
import cors from 'cors';
import { PredictionServiceClient } from '@google-cloud/aiplatform';
import { helpers } from '@google-cloud/aiplatform';

const app = express();
const PORT = process.env.PORT || 3001;

app.use(cors());
app.use(express.json());

// Vertex AI Configuration
const PROJECT_ID = process.env.GOOGLE_CLOUD_PROJECT_ID || 'humixo-thumbnail-maker';
const LOCATION = process.env.GOOGLE_CLOUD_LOCATION || 'us-central1';
const ENDPOINT = `projects/${PROJECT_ID}/locations/${LOCATION}/publishers/google/models/imagen-3.0-generate-001`;

// Initialize Vertex AI client (will use default credentials in Cloud Run)
const clientOptions = {
  apiEndpoint: `${LOCATION}-aiplatform.googleapis.com`,
};

const predictionServiceClient = new PredictionServiceClient(clientOptions);

app.post('/api/generate-image', async (req, res) => {
  try {
    const { prompt } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    console.log('Generating image with prompt:', prompt);

    // Prepare the request for Imagen 3
    const enhancedPrompt = `Create a high-quality, professional YouTube thumbnail image in 16:9 aspect ratio. ${prompt}. Make it vibrant, eye-catching, and optimized for YouTube with clear visual hierarchy, bold composition, and engaging elements that drive clicks.`;

    // Use helpers.toValue for proper formatting
    const instanceValue = helpers.toValue({
      prompt: enhancedPrompt,
    });

    const instances = [instanceValue];

    const parametersValue = helpers.toValue({
      sampleCount: 1,
      aspectRatio: '16:9',
      negativePrompt: 'blurry, low quality, distorted, ugly',
      safetySetting: 'block_some',
    });

    const request = {
      endpoint: ENDPOINT,
      instances,
      parameters: parametersValue,
    };

    console.log('Sending request to Vertex AI Imagen 3...');

    // Call Vertex AI Imagen
    const [response] = await predictionServiceClient.predict(request);
    
    console.log('Vertex AI Response received');
    
    if (!response.predictions || response.predictions.length === 0) {
      console.error('No predictions in response');
      throw new Error('No image generated by Vertex AI');
    }

    // Extract the base64 image from the response
    const prediction = response.predictions[0];
    
    // Imagen 3 returns the image in bytesBase64Encoded field
    let imageBytes = null;
    
    // Try different possible response formats
    if (prediction.bytesBase64Encoded) {
      imageBytes = prediction.bytesBase64Encoded;
    } else if (prediction.structValue?.fields?.bytesBase64Encoded?.stringValue) {
      imageBytes = prediction.structValue.fields.bytesBase64Encoded.stringValue;
    } else if (prediction.structValue?.fields?.image?.structValue?.fields?.bytesBase64Encoded?.stringValue) {
      imageBytes = prediction.structValue.fields.image.structValue.fields.bytesBase64Encoded.stringValue;
    }
    
    if (!imageBytes) {
      console.error('No image bytes found. Prediction keys:', Object.keys(prediction));
      throw new Error('Image data not found in response');
    }

    console.log('Image generated successfully');

    // Return the image as base64
    res.json({
      success: true,
      image: `data:image/png;base64,${imageBytes}`
    });

  } catch (error) {
    console.error('Error generating image:', error.message);
    console.error('Error details:', error);
    res.status(500).json({ 
      error: 'Failed to generate image',
      details: error.message 
    });
  }
});

app.get('/health', (req, res) => {
  res.json({ status: 'ok', message: 'Server is running', project: PROJECT_ID });
});

app.listen(PORT, () => {
  console.log(`Backend server running on port ${PORT}`);
  console.log(`Project ID: ${PROJECT_ID}`);
  console.log(`Location: ${LOCATION}`);
});
